### ISSUE TITLE
Specify the username and password doesn't work

### ISSUE THREAD

**Issue by beihaifeiwu** [avianey/hsqldb-maven-plugin#2]
I config the plugin like this:

``` xml
          <plugin>
            <!-- current version -->
            <groupId>fr.avianey.mojo</groupId>
            <artifactId>hsqldb-maven-plugin</artifactId>
            <version>1.0.0</version>
            <!--
                default value for in memory jdbc:hsqldb:hsql://localhost/xdb
                override only values you want to change
            -->
            <configuration>
              <driver>org.hsqldb.jdbcDriver</driver>
              <path>mem:test</path>
              <address>localhost</address>
              <name>xmbg_test</name>
              <username>root</username>
              <password>liupin</password>
              <validationQuery>SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS</validationQuery>
            </configuration>
            <!-- call start and stop -->
            <executions>
              <execution>
                <id>start-hsqldb</id>
                <phase>process-resources</phase>
                <goals>
                  <goal>start</goal>
                </goals>
              </execution>
              <execution>
                <id>stop-hsqldb</id>
                <phase>post-integration-test</phase>
                <goals>
                  <goal>stop</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
```

when I connect to it use the username and password specified, I got the exception

``` java
SqlException: invalid authorization specification - not found: root
```

Is it a bug or something ?

**Comment by avianey** [comment]
`mem` database are created with a `sa` user and no password by default.
You can't connect to it using alternate credential unless you specify those credential at database creation... You can either :
- use default credential  

``` xml
<username>sa</username>
<password></password>
```
- create the database with another username / password (try if it work)

``` xml
<path>mem:test;user=root;password=liupin</path>
```

or

``` xml
<name>xmbg_test;user=root;password=liupin</name>
```

**Comment by beihaifeiwu** [comment]
Not lucky, Neither solution works, exception is: 

``` java
[ERROR] Failed to execute goal com.freetmp:xmbg-maven-plugin:1.0.0:generate (default) on project xmbg-maven-plugin: SqlException: General error: database alias does not exist -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.freetmp:xmbg-maven-plugin:1.0.0:generate (default) on project xmbg-maven-plugin: SqlException: General error: database alias does not exist
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: SqlException: General error: database alias does not exist
        at com.freetmp.maven.mbg.extend.plugin.SqlScriptRunner.executeScript(SqlScriptRunner.java:99)
        at com.freetmp.maven.mbg.extend.plugin.MyBatisGeneratorMojo.runScriptIfNecessary(MyBatisGeneratorMojo.java:544)
        at com.freetmp.maven.mbg.extend.plugin.MyBatisGeneratorMojo.execute(MyBatisGeneratorMojo.java:218)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.sql.SQLException: General error: database alias does not exist
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
        at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
        at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at com.freetmp.maven.mbg.extend.plugin.SqlScriptRunner.executeScript(SqlScriptRunner.java:79)
        ... 24 more
Caused by: org.hsqldb.HsqlException: General error: database alias does not exist
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.ClientConnection.<init>(Unknown Source)
        ... 30 more
```
